server:
  port: 8080

spring:
  data:
    mongodb:
      port: 27017
      database: recommendation_db

kafka:
  topic:
    recommendation: recommendation

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
