server:
  port: 80

spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: kafka, mongo