server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 300000
      leak-detection-threshold: 2000

kafka:
  topic:
    review: review

