server:
  port: 80

spring:
  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: kafka, db