fullnameOverride: kafka

image:
  repository: registry.hub.docker.com/library
  name: confluentinc/cp-kafka
  tag: 6.1.9
  pullPolicy: IfNotPresent

env: 
  KAFKA_BROKER_ID: 1
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
  KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  

ports:
  - containerPort: 9092

service:
  ports:
    - port: 9092