server:
  port: 80

client:
  endpoints:
    sku:
      url: ${CLIENT_HOST_SKU}
    recommendation:
      url: ${CLIENT_HOST_RECOMMENATION}
    review:
      url: ${CLIENT_HOST_REVIEW}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: kafka